name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family:  Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    # Assets utama
    - assets/WebsiteLogo.jpg
    - assets/slanted_menu.jpg
    
    # Gambar custom dari folder assets (semua file .jpg)
    - assets/Alice.jpg
    - assets/Astra Yao.jpg
    - assets/Bronya.jpg
    - assets/Castorice.jpg
    - assets/Citali.jpg
    - assets/Elysia.jpg
    - assets/Evelyn.jpg
    - assets/FireFly.jpg
    - assets/Fu Xuan.jpg
    - assets/Kamisato Ayaka.jpg
    - assets/Kiana Kaslana.jpg
    - assets/Kokomi.jpg
    - assets/Lingsha.jpg
    - assets/Miyabi.jpg
    - assets/Nahida.jpg
    - assets/Nilou.jpg
    - assets/Raiden Mei.jpg
    - assets/Robin.jpg
    - assets/Silver Wolf.jpg
    - assets/Yuzuha.jpg
    - assets/Selle.jpg
    - assets/Navia.jpg
    - assets/Furina.jpg
    - assets/Belle.jpg
    - assets/Chiori.jpg
    - assets/Cipher.jpg
    - assets/Escoffier.jpg
    - assets/Ganyu.jpg
    - assets/Jean.jpg
    - assets/Keqing.jpg
    - assets/Mona.jpg
    - assets/Lumine.jpg
    - assets/Ruan Mei.jpg
    - assets/Shenhe.jpg
    - assets/Stelle.jpg
    - assets/Yixuan.jpg
    - assets/The Herta.jpg
    - assets/Sparkle.jpg
    - assets/Theresa.jpg
    - assets/Zhu Yuan.jpg
    - assets/Fu Hua.jpg